// supabase/functions/create-user-admin/index.ts

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const { email, password, phone, userData } = await req.json()

    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
      { auth: { autoRefreshToken: false, persistSession: false } }
    )

    // ── Verify caller ──────────────────────────────────────────────────────
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      return new Response(
        JSON.stringify({ success: false, message: 'No authorization header' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const token = authHeader.replace('Bearer ', '')
    const { data: { user: caller }, error: authError } = await supabaseAdmin.auth.getUser(token)

    if (authError || !caller) {
      return new Response(
        JSON.stringify({ success: false, message: 'Unauthorized' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const { data: callerData } = await supabaseAdmin
      .from('users')
      .select('user_type, is_active')
      .eq('auth_id', caller.id)
      .single()

    if (
      !callerData ||
      !['system_admin', 'super_admin', 'super_user', 'branch_admin'].includes(callerData.user_type) ||
      !callerData.is_active
    ) {
      return new Response(
        JSON.stringify({ success: false, message: 'Admin access required' }),
        { status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // ── Validate input ─────────────────────────────────────────────────────
    const isPhoneAccount = !!phone
    const isEmailAccount = !!email && !!password

    if (!isPhoneAccount && !isEmailAccount) {
      return new Response(
        JSON.stringify({ success: false, message: 'Provide either email+password or phone' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // ── Resolve password for phone accounts ──────────────────────────────────
    // Use the caller-supplied password if provided; otherwise auto-generate one.
    let resolvedPassword: string | null = null
    let wasPasswordAutoGenerated = false
    if (isPhoneAccount) {
      const rawPassword = password != null && password !== undefined ? String(password).trim() : ''
      if (rawPassword.length >= 1) {
        resolvedPassword = rawPassword
      } else {
        const firstName = ((userData?.full_name as string) ?? 'user')
          .trim()
          .split(/\s+/)[0]
          .toLowerCase()
          .replace(/[^a-z0-9]/g, '')
        const sixDigits = Math.floor(100000 + Math.random() * 900000).toString()
        resolvedPassword = firstName + sixDigits
        wasPasswordAutoGenerated = true
      }
    }

    // ── Create Supabase Auth user ──────────────────────────────────────────
    const profileEmail = isEmailAccount
      ? email
      : `phone_${(phone as string).replace(/\D/g, '')}@phone.user`

    const createPayload: Record<string, unknown> = {
      email_confirm: true,
      phone_confirm: true,
      user_metadata: { full_name: userData?.full_name },
    }

    if (isPhoneAccount) {
      // Phone users get placeholder email + resolved password so they can log in
      createPayload.email = profileEmail
      createPayload.password = resolvedPassword
      createPayload.phone = phone
    } else {
      createPayload.email = email
      createPayload.password = password
    }

    const { data: authData, error: authUserError } =
      await supabaseAdmin.auth.admin.createUser(createPayload as Parameters<typeof supabaseAdmin.auth.admin.createUser>[0])

    if (authUserError || !authData.user) {
      throw authUserError || new Error('Failed to create auth user')
    }

    // ── Insert profile row ─────────────────────────────────────────────────
    const { data: dbUser, error: dbError } = await supabaseAdmin
      .from('users')
      .insert({
        auth_id: authData.user.id,
        email: profileEmail,
        ...userData,
      })
      .select()
      .single()

    if (dbError) {
      // Roll back auth user on profile insert failure
      await supabaseAdmin.auth.admin.deleteUser(authData.user.id)
      throw dbError
    }

    return new Response(
      JSON.stringify({
        success: true,
        user_id: dbUser.id,
        auth_id: authData.user.id,
        message: 'User created successfully',
        ...(wasPasswordAutoGenerated ? { generated_password: resolvedPassword } : {}),
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )

  } catch (error) {
    return new Response(
      JSON.stringify({ success: false, message: error.message }),
      { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})
