// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Q9O8IjJZic-87u8HWP5dcqxL0uEnmRQ',
    appId: '1:532032178313:web:7dc2298d4b54f00517de58',
    messagingSenderId: '532032178313',
    projectId: 'jalaticketing',
    authDomain: 'jalaticketing.firebaseapp.com',
    storageBucket: 'jalaticketing.firebasestorage.app',
    measurementId: 'G-7C8Y3NKVDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAmxU1xpOSLDuUneUc3Lwy7_3lEJvZRnc',
    appId: '1:532032178313:android:78385a2ef71f3d9117de58',
    messagingSenderId: '532032178313',
    projectId: 'jalaticketing',
    storageBucket: 'jalaticketing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWVs1q-CNbORicLPy_jYiVHkt-EnsVQ54',
    appId: '1:532032178313:ios:92c7474e3d695bfa17de58',
    messagingSenderId: '532032178313',
    projectId: 'jalaticketing',
    storageBucket: 'jalaticketing.firebasestorage.app',
    iosBundleId: 'com.example.jalasupport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWVs1q-CNbORicLPy_jYiVHkt-EnsVQ54',
    appId: '1:532032178313:ios:92c7474e3d695bfa17de58',
    messagingSenderId: '532032178313',
    projectId: 'jalaticketing',
    storageBucket: 'jalaticketing.firebasestorage.app',
    iosBundleId: 'com.example.jalasupport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_Q9O8IjJZic-87u8HWP5dcqxL0uEnmRQ',
    appId: '1:532032178313:web:5ff5ea73af6274d617de58',
    messagingSenderId: '532032178313',
    projectId: 'jalaticketing',
    authDomain: 'jalaticketing.firebaseapp.com',
    storageBucket: 'jalaticketing.firebasestorage.app',
    measurementId: 'G-1F50MLRMYP',
  );

}